# --- !Ups

CREATE TABLE "USUARIO" (
  "ID" SERIAL NOT NULL PRIMARY KEY,
  "NOMBRE" VARCHAR NOT NULL,
  "DOCUMENTO" VARCHAR UNIQUE NOT NULL,
  "SEXO" VARCHAR NULL,
  "FECHANAC" DATE NULL,
  "EDAD" INT NOT NULL,
  "DIRECCIONDOM" VARCHAR NOT NULL,
  "CORREO" VARCHAR NOT NULL,
  "TELEFONO" VARCHAR NULL,
  "CELULAR" VARCHAR NULL,
  "USERINSERT" VARCHAR NULL,
  "MODIFICACION" TIMESTAMP NULL,
  "GCMID" VARCHAR NULL,
  "CLAVE" VARCHAR NULL,
  "ROL" VARCHAR NOT NULL
  );

# --- !Downs

drop table "USUARIO";